spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/laonstory?serverTimezone=UTC&characterEncoding=UTF-8
    username: chan
    password: qwer2009

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

